# Display (nice!view MIP via nice_view_gem module)
# Widgets: active layer, BT status, battery level
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_VIEW_GEM_ANIMATION=n

# ZMK Studio
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO=y

# Bluetooth TX power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
